Repository Azure/k8s-bake, pull requests merged in 2025-07, with the labels that each got.

#163 Add husky pre-commit hook.
  .husky/pre-commit
  package-lock.json
  package.json
Labels: enhancement

#171 Update CODEOWNERS on main
  .github/CODEOWNERS
Labels: enhancement, github_actions

#168 Adding a check for cached version #98
  src/kubectl-util.test.ts
  src/kubectl-util.ts
Labels: bug

#169 added warning for mistaken separators#97
  src/bake.test.ts
  src/bake.ts
Labels: enhancement
